<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./src/scss/bootstrap.min.css">
    <link rel="stylesheet" href="./src/scss/shamba.css">
    <title>ShambaPro</title>
</head>
<body >
<div class="container-xxl">
<div class="sunfarm py-4">
    <div class="row pt-sm-5 pt-3 ">
        <div class="col-sm-6 text-start">
    <h1>SUNSHINE FARM LTD</h1>
    <h2 class="mb-1" style="font-size: 22px !important;">Farm Inventory Report</h2>
    <h3 class="mb-1" style="font-size: 14px !important;">For the year ended December 31st 2022</h3>
</div>
<div class="col-sm-6 text-sm-end pt-sm-0 pt-3">
    <p class=" text-dark mb-2">Generated by</p>
<img src="./src/imgs/logos/shambapro.webp" alt="">
<p class=" text-dark mb-0">On 5th November 2021</p>
</div>
</div>
</div>
<div class="row report-details">
    <div class="col-sm-3">
        <p>Name:<span class="ps-1">Andrew</span></p>
    </div>
    <div class="col-sm-3">
        <p>Creation Date:<span class="ps-1">01 Feb, 2023</span></p>
    </div>
    <div class="col-sm-3 text-sm-end">
        <p>Category:<span class="ps-1">Livestock</span></p>
    </div>
    <div class="col-sm-3 text-sm-end">
        <p>Sub-Category:<span class="ps-1">Animals</span></p>
    </div>
</div>
<div class="table-responsive border-top">
    <div class="text-center farmstock">
        FARM STOCK
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Quantity</th>
            </tr>
        </thead>
        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>Animals</td>
                <td>Livestock</td>
                <td>20</td>
            </tr>
            <tr class="dashed-border">
                <td>Animals</td>
                <td>Livestock</td>
                <td>20</td>
            </tr>
            <tr class="dashed-border">
                <td>Animals</td>
                <td>Livestock</td>
                <td>20</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        FARM INPUTS
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Total Quantity</th>
                <th scope="col">Remaining Quantity</th>
                <th scope="col">Used Quantity</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>1234</td>
                <td>Feed</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Feed</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Feed</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        Farm Machinery
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Total Quantity</th>
                <th scope="col">Sold</th>
                <th scope="col">Remaining</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            <tr class="dashed-border">
                <td>123</td>
                <td>Tractor</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>123</td>
                <td>Tractor</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>123</td>
                <td>Tractor</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
        </tbody>
    
        
     
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        Building & Structures
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Total Quantity</th>
                <th scope="col">In Use</th>
                <th scope="col">Free Space</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>1234</td>
                <td>Office</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Office</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Office</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
        </tbody>
    
        
     
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        Farm Land
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Total Quantity</th>
                <th scope="col">In Use</th>
                <th scope="col">Free Space</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>123</td>
                <td>Sheds</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>123</td>
                <td>Sheds</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>123</td>
                <td>Sheds</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        Office Equipment
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Total Quantity</th>
                <th scope="col">Sold</th>
                <th scope="col">Remaining</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>1234</td>
                <td>Printer</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Printer</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
            <tr class="dashed-border">
                <td>1234</td>
                <td>Printer</td>
                <td>20</td>
                <td>15</td>
                <td>05</td>
            </tr>
        </tbody>
    </table>
</div>
<p class="py-3 paragraph mb-0">This report has been generated by the Shambapro Digital Agriculture Platform.
     All information in this report belongs to the Farm Owner</p>

</div>    

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="./src/js/bootstrap.bundle.min.js"></script>
</body>
</html>