<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ asset('src/scss/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ asset('src/scss/shamba.css')}}">
    <title>ShambaPro</title>
</head>
<body>
<div class="container-xxl">
<div class="text-center sunfarm py-5">
    <h1>SUNSHINE FARM LTD</h1>
    <h2 class="mb-1">INCOME STATEMENT</h2>
    <h3 class="mb-1">FOR THE YEAR ENDED DECEMBER 31ST {{Carbon\Carbon::now()->format('Y')}}</h3>
    <p>Generated by<span class="px-2"><img src="{{ asset('src/imgs/logos/ShambaLogo.png')}}" alt=""></span>On {{Carbon\Carbon::now()->format('d M Y')}} </p>

</div>
<div class="table-responsive container-xxl">
    <table class="table table-borderless" rules="all" id="printTable">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col" class="text-end" style="min-width: 100px;">Current Period</th>
                <!-- <th scope="col" class="text-end">YTD</th> -->
            </tr>
        </thead>
        <tbody class="table-group-divider TableHeading">
            <tr class="dashed-border ">
                <th scope="col ">Gross Profit/Income</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            
            <tr class="dashed-border">
                <td>Product Sales (Regular Income/Sales)</td>
                <td class="text-end color-dark">{{$product_sale->product_sale}}</td>
                <td class="text-end color-dark"></td>
            </tr>
            <tr class="dashed-border">
                <td>Costs of Goods Sold (Farm Inputs & Farm Services)</td>
                <td class="text-end color-dark">{{$costs_goods_sold->costs_goods_sold}}</td>
                <td class="text-end color-dark"></td>
            </tr>
            <tr class="dashed-border">
                <td>Gross Profit/Income (Total)</td>
                <td class="text-end color-dark">{{$gross_profit_income}}</td>
                <td class="text-end color-dark"></td>
            </tr>
            
        </tbody>
        <tbody class="table-group-divider TableHeading">
            <tr class="dashed-border ">
                <th scope="col ">Operating Profit/Income</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            <tr class="dashed-border">
                <td>Gross Profit</td>
                <td class="text-end color-dark">{{$gross_profit_income}}</td>
                <td class="text-end"></td>
            </tr>
            <tr class="dashed-border">
                <td>Operating Expenses (Monthly Payments & Expenses)</td>
                <td class="text-end color-dark ">{{ $operating_expenses->operating_expenses }} </td>
                <td class="text-end"></td>
            </tr>
            <tr class="dashed-border">
                <td>Operating Profit/Income (Total)</td>
                <td class="text-end color-dark">{{ $operating_profit_income }}</td>
                <td class="text-end"></td>
            </tr>
            
        </tbody>
        <tbody class="table-group-divider TableHeading">
            <tr class="dashed-border ">
                <th scope="col ">Net Profit/Income before Taxes</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            <tr class="dashed-border">
                <td>Operating Profit/Income   </td>
                <td class="text-end color-dark ">{{ $operating_profit_income }} </td>
                <td class="text-end"></td>
            </tr>
            <tr class="dashed-border">
                <td>Non-Operating Income   </td>
                <td class="text-end color-dark">{{$non_operating_income->non_operating_income}} </td>
                <td class="text-end"></td>
            </tr>
            <tr class="dashed-border">
                <td>Non-Operating Expenses   </td>
                <td class="text-end color-dark">{{$non_operating_expenses->non_operating_expenses}} </td>
                <td class="text-end"></td>
            </tr>
            <tr class="dashed-border">
                <td>Net Profit/Income before Taxes (Total)  </td>
                <td class="text-end color-dark">{{$net_profit_income_before_taxes}} </td>
                <td class="text-end"></td>
            </tr>
        </tbody>
        <tbody class="table-group-divider ">
            <tr class="dashed-border transparentcolor">
                <th scope="col ">a</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
           
            <tr class="dashed-border">
                <td>Income Tax</td>
                <td class="text-end color-dark">{{$income_tax }} </td>
                <td class="text-end"></td>
            </tr>
            <tr class="footer-border ">
                <td scope="col" class="font-dark">Net Profit/Income</td>
                <td scope="col" class="text-end font-dark">{{$net_profit_income}}</td>
                <td scope="col" class="text-end"></td>
            </tr>
           
        </tbody>
    </table>
    <p class="py-3">This report has been generated by the Shambapro Digital Agriculture Platform.
        All information in this report belongs to the Farm Owner and can only be
        shared with third parties with their express permission. For more information,
        contact hello@shambapro.com or visit www.shambapro.com</p>
</div>
</div>    

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="{{ asset('src/js/bootstrap.bundle.min.js')}}"></script>
</body>
</html>