<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./src/scss/bootstrap.min.css">
    <link rel="stylesheet" href="./src/scss/shamba.css">
    <title>ShambaPro</title>
</head>
<body >
<div class="container-xxl">
<div class="sunfarm py-4">
    <div class="row pt-sm-5 pt-3 ">
        <div class="col-sm-6 text-start">
    <h1>SUNSHINE FARM LTD</h1>
    <h2 class="mb-1" style="font-size: 22px !important;">Farm Production Report</h2>
    <h3 class="mb-1" style="font-size: 14px !important;">For the year ended December 31st 2022</h3>
</div>
<div class="col-sm-6 text-sm-end pt-sm-0 pt-3">
    <p class=" text-dark mb-2">Generated by</p>
<img src="./src/imgs/logos/shambapro.webp" alt="">
<p class=" text-dark mb-0">On 5th November 2021</p>
</div>
</div>
</div>
<div class="row report-details">
    <div class="col-sm-3">
        <p>Name:<span class="ps-1">Andrew</span></p>
    </div>
    <div class="col-sm-3">
        <p>Creation Date:<span class="ps-1">01 Feb, 2023</span></p>
    </div>
    <div class="col-sm-3 text-sm-end">
        <p>Category:<span class="ps-1">Livestock</span></p>
    </div>
    <div class="col-sm-3 text-sm-end">
        <p>Sub-Category:<span class="ps-1">Cattle(Diary)</span></p>
    </div>
</div>
<div class="table-responsive border-top">
    <div class="text-center farmstock">
        Feeding Records - Daily Production Records
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">Date</th>
                <th scope="col">Animal ID</th>
                <th scope="col">Type</th>
                <th scope="col">Quantity</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>Feed 3</td>
                <td>20</td>
            </tr>
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>Feed 3</td>
                <td>20</td>
            </tr>
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>Feed 3</td>
                <td>20</td>
            </tr>
        </tbody>
    </table>
</div>
<div class="table-responsive">
    <div class="text-center farmstock">
        Feeding Records - Daily Grazing Record
    </div>
    <table class="table table-bordered border-dark invoice2 mb-0">
        <thead class="TableHeader">
            <tr >
                <th scope="col">Date</th>
                <th scope="col">Animal ID</th>
                <th scope="col">Grazing From</th>
                <th scope="col">Grazing To</th>
            </tr>
        </thead>

        <tbody class="TableBody">
            
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>1 February, 2023</td>
                <td>1 February, 2023</td>
            </tr>
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>1 February, 2023</td>
                <td>1 February, 2023</td>
            </tr>
            <tr class="dashed-border">
                <td>1 February, 2023</td>
                <td>Beef-123</td>
                <td>1 February, 2023</td>
                <td>1 February, 2023</td>
            </tr>
        </tbody>
    </table>
</div>
<p class="py-3 paragraph">This report has been generated by the Shambapro Digital Agriculture Platform.
     All information in this report belongs to the Farm Owner</p>

</div>    

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="./src/js/bootstrap.bundle.min.js"></script>
</body>
</html>