<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./src/scss/bootstrap.min.css" />
    <link rel="stylesheet" href="./src/scss/shamba.css" />
    <title>ShambaPro</title>
  </head>
  <body>
    <div class="container-xxl">
      <div class="sunfarm pt-4 pb-2">
        <div class="row pt-sm-5 pt-3">
          <div class="col-sm-6 text-start">
            <h1>SUNSHINE FARM LTD</h1>
            <h2 class="mb-1" style="font-size: 22px !important">
              STAFF PERFORMANCE REPORT
            </h2>
            <h3 class="mb-1" style="font-size: 14px !important">
              For the year ended December 31st 2022
            </h3>
          </div>
          <div class="col-sm-6 text-sm-end pt-sm-0 pt-3">
            <p class="text-dark mb-2">Generated by</p>
            <img src="./src/imgs/logos/shambapro.webp" alt="" />
            <p class="text-dark mb-0">On 5th November 2021</p>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <div class="text-center farmstock">
            Tasks/Jobs
        </div>
        <table class="table table-bordered border-dark invoice2 mb-0">
          <thead class="TableHeader">
            <tr>
              <th scope="col">Date</th>
              <th scope="col">Jobs Name</th>
              <th scope="col">Team Member</th>
              <th scope="col">Approval Level</th>
              <th scope="col">Actions to be Taken</th>
              <th scope="col">Comments</th>
            </tr>
          </thead>
          <tbody class="TableBody">
            <tr class="dashed-border">
              <td>2 Jan, 2023</td>
              <td>Jobs Name</td>
              <td>Andrew</td>
              <td>Pending</td>
              <td>Actions</td>
              <td>Comments</td>
            </tr>
            <tr class="dashed-border">
              <td>2 Jan, 2023</td>
              <td>Jobs Name</td>
              <td>Andrew</td>
              <td>Pending</td>
              <td>Actions</td>
              <td>Comments</td>
            </tr>
            <tr class="dashed-border">
              <td>2 Jan, 2023</td>
              <td>Jobs Name</td>
              <td>Andrew</td>
              <td>Pending</td>
              <td>Actions</td>
              <td>Comments</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="table-responsive">
        <div class="text-center farmstock">
            Tasks Summery
        </div>
        <table class="table table-bordered border-dark invoice2 mb-0">
          <thead class="TableHeader">
            <tr>
              <th scope="col">Team member</th>
              <th scope="col">Total Tasks</th>
              <th scope="col">Very Satisfied</th>
              <th scope="col">Fairly Satisfied</th>
              <th scope="col">To Be Repeated</th>
              <th scope="col">To Be Reallocated</th>
            </tr>
          </thead>
          <tbody class="TableBody">
            <tr class="dashed-border">
              <td>Mamber Name</td>
              <td>10</td>
              <td>3</td>
              <td>2</td>
              <td>2</td>
              <td>3</td>
            </tr>
            <tr class="dashed-border">
              <td>Mamber Name</td>
              <td>10</td>
              <td>3</td>
              <td>2</td>
              <td>2</td>
              <td>3</td>
            </tr>
            <tr class="dashed-border">
              <td>Mamber Name</td>
              <td>10</td>
              <td>3</td>
              <td>2</td>
              <td>2</td>
              <td>3</td>
            </tr>
          </tbody>
        </table>
      </div>
      <p class="py-3 paragraph mb-0">
        This report has been generated by the Shambapro Digital Agriculture Platform. All information in this report belongs to the Farm Owner
      </p>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous"
    ></script>
    <script src="./src/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
